name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "20439790-1e79b20e-bfe0-48a1-8948-14ac476b1e1d" -e "20439790-84466352-fcda-46c0-a762-0c0b9901705d" --integration-id "154969-${{ github.run_id }}"
